# Generated by Django 5.2.8 on 2025-11-28 15:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text="Unique code for the app (e.g., 'USER_MGMT', 'REPORTS')", max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, help_text='Icon class or URL', max_length=100, null=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which app appears in menus')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_apps', to='users_auth.user')),
                ('parent_app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_apps', to='rbac.app')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'db_table': 'rbac_app',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('ASSIGN', 'Assign'), ('REVOKE', 'Revoke'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('ACCESS', 'Access'), ('DENY', 'Deny')], max_length=20)),
                ('entity_type', models.CharField(choices=[('USER_ROLE', 'User Role'), ('APP', 'Application'), ('FEATURE', 'Feature'), ('ROLE_APP_MAPPING', 'Role-App Mapping'), ('ROLE_FEATURE_MAPPING', 'Role-Feature Mapping'), ('USER_ROLE_ASSIGNMENT', 'User Role Assignment'), ('ROLE_HIERARCHY', 'Role Hierarchy')], max_length=50)),
                ('entity_id', models.IntegerField()),
                ('entity_uuid', models.UUIDField(blank=True, null=True)),
                ('description', models.TextField()),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rbac_audit_logs', to='users_auth.user')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'rbac_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text="Unique code within the app (e.g., 'CREATE_USER', 'VIEW_REPORT')", max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('feature_type', models.CharField(choices=[('ACTION', 'Action'), ('VIEW', 'View'), ('REPORT', 'Report'), ('SETTING', 'Setting'), ('OTHER', 'Other')], default='ACTION', max_length=20)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='rbac.app')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_features', to='users_auth.user')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'db_table': 'rbac_feature',
                'ordering': ['app', 'display_order', 'name'],
                'unique_together': {('app', 'code')},
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text="Unique code for the role (e.g., 'DEVELOPER', 'SUPER_ADMIN')", max_length=50, unique=True)),
                ('level', models.IntegerField(choices=[(1, 'Developer'), (2, 'Super Admin'), (3, 'Admin'), (4, 'Client'), (5, 'End User')], default=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_system_role', models.BooleanField(default=False, help_text='System roles cannot be deleted')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_roles', to='users_auth.user')),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
                'db_table': 'rbac_user_role',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserRoleAssignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_primary', models.BooleanField(default=False, help_text="Is this the user's primary role?")),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, help_text='Leave empty for permanent assignment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_user_roles', to='users_auth.user')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='rbac.userrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='users_auth.user')),
            ],
            options={
                'verbose_name': 'User Role Assignment',
                'verbose_name_plural': 'User Role Assignments',
                'db_table': 'rbac_user_role_assignment',
                'ordering': ['-is_primary', 'role__level'],
            },
        ),
        migrations.CreateModel(
            name='RoleHierarchy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('can_assign', models.BooleanField(default=True, help_text='Can assign this role to users')),
                ('can_revoke', models.BooleanField(default=True, help_text='Can revoke this role from users')),
                ('can_modify_permissions', models.BooleanField(default=False, help_text='Can modify permissions of this role')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_role_hierarchies', to='users_auth.user')),
                ('child_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_role_relations', to='rbac.userrole')),
                ('parent_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_role_relations', to='rbac.userrole')),
            ],
            options={
                'verbose_name': 'Role Hierarchy',
                'verbose_name_plural': 'Role Hierarchies',
                'db_table': 'rbac_role_hierarchy',
                'unique_together': {('parent_role', 'child_role')},
            },
        ),
        migrations.CreateModel(
            name='RoleFeatureMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('can_view', models.BooleanField(default=True)),
                ('can_create', models.BooleanField(default=False)),
                ('can_update', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_role_feature_mappings', to='users_auth.user')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_feature_mappings', to='rbac.feature')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_feature_mappings', to='rbac.userrole')),
            ],
            options={
                'verbose_name': 'Role-Feature Mapping',
                'verbose_name_plural': 'Role-Feature Mappings',
                'db_table': 'rbac_role_feature_mapping',
                'unique_together': {('role', 'feature')},
            },
        ),
        migrations.CreateModel(
            name='RoleAppMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('can_view', models.BooleanField(default=True)),
                ('can_create', models.BooleanField(default=False)),
                ('can_update', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_app_mappings', to='rbac.app')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_role_app_mappings', to='users_auth.user')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_app_mappings', to='rbac.userrole')),
            ],
            options={
                'verbose_name': 'Role-App Mapping',
                'verbose_name_plural': 'Role-App Mappings',
                'db_table': 'rbac_role_app_mapping',
                'unique_together': {('role', 'app')},
            },
        ),
    ]
