# Generated by Django 5.2.8 on 2025-11-28 16:35

from django.db import migrations, models
import string
import random


def generate_unique_codes(apps, schema_editor):
    """Generate unique user codes for existing users"""
    User = apps.get_model('users_auth', 'User')
    characters = string.ascii_uppercase + string.digits
    
    existing_codes = set()
    for user in User.objects.all():
        # Generate unique code
        while True:
            code = ''.join(random.choices(characters, k=6))
            if code not in existing_codes:
                existing_codes.add(code)
                user.user_code = code
                user.save(update_fields=['user_code'])
                break


def reverse_codes(apps, schema_editor):
    """Reverse migration - nothing to do"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0001_initial'),
    ]

    operations = [
        # First add user_code without unique constraint
        migrations.AddField(
            model_name='user',
            name='user_code',
            field=models.CharField(blank=True, default='', help_text='Unique user code (auto-generated if not provided)', max_length=20),
        ),
        # Add user_role field
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('DEVELOPER', 'Developer'), ('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('CLIENT', 'Client'), ('END_USER', 'End User')], default='END_USER', help_text='Primary role of the user', max_length=20),
        ),
        # Generate unique codes for existing users
        migrations.RunPython(generate_unique_codes, reverse_codes),
        # Now add the unique constraint
        migrations.AlterField(
            model_name='user',
            name='user_code',
            field=models.CharField(blank=True, help_text='Unique user code (auto-generated if not provided)', max_length=20, unique=True),
        ),
    ]
