# Generated by Django 5.2.8 on 2025-12-02 15:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0002_user_user_code_user_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='last_activity',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(db_index=True, max_length=255)),
                ('identifier_type', models.CharField(choices=[('EMAIL', 'Email'), ('USERNAME', 'Username'), ('USER_CODE', 'User Code'), ('PHONE', 'Phone Number')], max_length=20)),
                ('attempt_count', models.IntegerField(default=0)),
                ('lockout_stage', models.IntegerField(default=0)),
                ('is_successful', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('lockout_until', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_attempts', to='users_auth.user')),
            ],
            options={
                'db_table': 'users_auth_login_attempt',
                'ordering': ['-last_attempt_at'],
                'indexes': [models.Index(fields=['identifier', 'identifier_type'], name='users_auth__identif_32ba97_idx'), models.Index(fields=['ip_address'], name='users_auth__ip_addr_999866_idx')],
            },
        ),
    ]
