# Generated by Django 5.2.8 on 2025-12-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0003_enhanced_login_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when user was soft deleted', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag - True means user is deleted'),
        ),
    ]
