# Generated by Django 5.2.8 on 2025-12-05 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0004_add_soft_delete_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login Failed'), ('REGISTER', 'Registration'), ('PASSWORD_CHANGE', 'Password Change'), ('PASSWORD_RESET', 'Password Reset'), ('PROFILE_UPDATE', 'Profile Update'), ('KYC_SUBMIT', 'KYC Submission'), ('KYC_APPROVED', 'KYC Approved'), ('KYC_REJECTED', 'KYC Rejected'), ('ACCESS_ASSIGNED', 'Access Assigned'), ('ACCESS_REVOKED', 'Access Revoked'), ('ROLE_CHANGED', 'Role Changed'), ('API_CALL', 'API Call'), ('PAGE_VISIT', 'Page Visit'), ('CREATE', 'Create Action'), ('UPDATE', 'Update Action'), ('DELETE', 'Delete Action'), ('VIEW', 'View Action'), ('EXPORT', 'Export Action'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('action', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('entity_type', models.CharField(blank=True, help_text='Type of entity affected (e.g., User, KYC, Role)', max_length=100)),
                ('entity_id', models.CharField(blank=True, help_text='ID of entity affected', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('is_success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='users_auth.user')),
            ],
            options={
                'db_table': 'users_auth_activity_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='users_auth__user_id_ae1e65_idx'), models.Index(fields=['activity_type', '-created_at'], name='users_auth__activit_70fc90_idx'), models.Index(fields=['entity_type', 'entity_id'], name='users_auth__entity__01b553_idx'), models.Index(fields=['-created_at'], name='users_auth__created_489fbc_idx')],
            },
        ),
    ]
