# Generated by Django 4.2.20 on 2026-01-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0005_user_email_verified_at_user_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_otp',
            field=models.CharField(blank=True, help_text='Email OTP code', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_otp_attempt_count',
            field=models.IntegerField(default=0, help_text='Number of OTP verification attempts'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_otp_created_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when email OTP was generated', null=True),
        ),
    ]
