# Generated by Django 4.2.20 on 2026-01-11 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users_auth', '0006_user_email_otp_user_email_otp_attempt_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email_type', models.CharField(max_length=50, unique=True)),
                ('subject_template', models.CharField(max_length=255)),
                ('html_template', models.TextField()),
                ('plain_text_template', models.TextField()),
                ('available_variables', models.JSONField(default=dict, help_text='JSON dict of available variables for this template')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'email_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('otp_verification', 'otp_verification'), ('welcome', 'welcome'), ('password_reset', 'password_reset'), ('password_reset_confirmation', 'password_reset_confirmation'), ('kyc_pending_reminder', 'kyc_pending_reminder'), ('kyc_rejection', 'kyc_rejection'), ('kyc_completion_welcome', 'kyc_completion_welcome'), ('support_ticket_auto_reply', 'support_ticket_auto_reply'), ('maintenance', 'maintenance'), ('important_notice', 'important_notice')], help_text='Type of email sent', max_length=50)),
                ('recipient_email', models.EmailField(help_text='Email address of recipient', max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('queued', 'Queued')], default='pending', max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=2)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('last_retry_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_user', models.ForeignKey(blank=True, help_text='User who received the email (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_emails', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(blank=True, help_text='User who triggered the email (for admin-sent emails)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email_type', 'status'], name='email_logs_email_t_022709_idx'), models.Index(fields=['recipient_email', '-created_at'], name='email_logs_recipie_d24bb8_idx'), models.Index(fields=['status', 'created_at'], name='email_logs_status_abf152_idx'), models.Index(fields=['priority', 'status'], name='email_logs_priorit_ab42e1_idx')],
            },
        ),
    ]
