# Generated by Django 4.2.20 on 2026-01-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0007_emailtemplate_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_otp',
            field=models.CharField(blank=True, help_text='Password reset OTP code', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_otp_attempt_count',
            field=models.IntegerField(default=0, help_text='Number of password reset OTP verification attempts'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_otp_created_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when password reset OTP was generated', null=True),
        ),
    ]
