# Generated by Django 4.2.20 on 2025-12-09 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_auth', '0005_user_email_verified_at_user_is_email_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bill Category',
                'verbose_name_plural': 'Bill Categories',
                'db_table': 'bill_categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Biller',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='billers/logos/')),
                ('min_amount', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=2, default=100000.0, max_digits=10)),
                ('required_fields', models.JSONField(blank=True, default=dict)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('platform_fee_type', models.CharField(choices=[('FIXED', 'Fixed'), ('PERCENTAGE', 'Percentage')], default='FIXED', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billers', to='bill_pay.billcategory')),
            ],
            options={
                'verbose_name': 'Biller',
                'verbose_name_plural': 'Billers',
                'db_table': 'billers',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BillFetchLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('consumer_number', models.CharField(max_length=100)),
                ('request_data', models.JSONField(default=dict)),
                ('response_data', models.JSONField(default=dict)),
                ('is_success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('biller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bill_pay.biller')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_fetch_logs', to='users_auth.user')),
            ],
            options={
                'verbose_name': 'Bill Fetch Log',
                'verbose_name_plural': 'Bill Fetch Logs',
                'db_table': 'bill_fetch_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedBiller',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('consumer_number', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('is_autopay_enabled', models.BooleanField(default=False)),
                ('autopay_amount_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('biller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill_pay.biller')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_billers', to='users_auth.user')),
            ],
            options={
                'verbose_name': 'Saved Biller',
                'verbose_name_plural': 'Saved Billers',
                'db_table': 'saved_billers',
                'unique_together': {('user', 'biller', 'consumer_number')},
            },
        ),
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('consumer_number', models.CharField(max_length=100)),
                ('consumer_name', models.CharField(blank=True, max_length=200)),
                ('consumer_details', models.JSONField(blank=True, default=dict)),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('bill_number', models.CharField(blank=True, max_length=100)),
                ('bill_period', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], default='INITIATED', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('payment_gateway_ref', models.CharField(blank=True, max_length=100)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('biller_ref_number', models.CharField(blank=True, max_length=100)),
                ('biller_response', models.JSONField(blank=True, default=dict)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('refund_details', models.JSONField(blank=True, default=dict)),
                ('biller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='bill_pay.biller')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_payments', to='users_auth.user')),
            ],
            options={
                'verbose_name': 'Bill Payment',
                'verbose_name_plural': 'Bill Payments',
                'db_table': 'bill_payments',
                'ordering': ['-initiated_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='bill_paymen_user_id_fa88cf_idx'), models.Index(fields=['biller', 'status'], name='bill_paymen_biller__93ce11_idx'), models.Index(fields=['transaction_id'], name='bill_paymen_transac_48200b_idx'), models.Index(fields=['consumer_number'], name='bill_paymen_consume_cb67cf_idx')],
            },
        ),
    ]
